# 1: I hate myself for having to rewrite this tchotchke little functionality every damn time!
# 2: Reminding myself the annoying *import trivia* regaring the matlib sub-package.
## Link: https://stackoverflow.com/questions/41818379/why-do-i-have-to-import-this-from-numpy-if-i-am-just-referencing-it-from-the-num
![title](matlib.png)

In [1]:
import numpy as np
import numpy.matlib as matlib

X=matlib.repmat([0,1,2],3,8).T
y=np.array(8*[0,1,2])
(X,y)

(array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
        2]))

In [2]:
from sklearn.model_selection import StratifiedKFold
# For a 80-20 split
def split_class_aware(X,y,n_splits=2):
    
    skf = StratifiedKFold(n_splits,shuffle=True)
    ind_split=skf.split(np.zeros(24), y)
    train_index=ind_split.next()[0]
    test_index=ind_split.next()[1]
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    return (X_train, X_test,y_train, y_test)

In [3]:
X_train, X_test,y_train, y_test=split_class_aware(X,y,n_splits=4)
############################
print(X_test[:,0]-y_test)
print(X_test[:,0]-y_test)
############################

[0 0 0 0 0 0]
[0 0 0 0 0 0]
